//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelOtomasyon.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRezervasyon
    {
        public string TC { get; set; }
        public string Musteri { get; set; }
        public string Telefon { get; set; }
        public string Yas { get; set; }
        public string GirisTarih { get; set; }
        public string CikisTarih { get; set; }
        public string Cocuk { get; set; }
        public string Yetiskin { get; set; }
        public string OdaTipi { get; set; }
        public Nullable<int> Fiyat { get; set; }
    }
}
